version: '3'

services:

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
  
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

  nginx:
      build:
        context: .
        dockerfile: requirements/nginx/Dockerfile
      container_name: nginx
      depends_on:
        - wordpress
      ports:
        - "443:443"
      networks:
        - inception
      volumes:
        - ./requirements/nginx/conf/:/etc/nginx/http.d/
        - ./requirements/nginx/tools:/etc/nginx/ssl/
        - wp-volume:/var/www/
      restart: always

volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

networks:
    inception:
        driver: bridge