version: '3'

services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html
    restart: always

  nginx:
      build: ./requirements/nginx
      container_name: nginx
      env_file:
        - .env
      depends_on:
        - wordpress
      ports:
        - "443:443"
      networks:
        - inception
      volumes:
        - wp-volume:/var/www/html
      restart: always

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yback/data/mariadb
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yback/data/wordpress

networks:
    inception:
        driver: bridge