-- ALTER USER 'root'@'%' IDENTIFIED BY '${DB_ROOT}';
-- FLUSH PRIVILEGES;

CREATE DATABASE IF '${DB_NAME}';
CREATE USER IF '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;

